title: Gongyue Teng's Homepage
page-top-title: Gongyue Teng
top-section-bg-text: Gongyue Teng's Homepage
home-subtitle: Yourname&ensp;|&ensp;滕宫阅
copyright-text: '&copy; gongyueteng 2023-2025. All Rights Reserved.'
