title: Gongyue Teng's Homepage
page-top-title: Gongyue Teng
top-section-bg-text: Solving real problems with elegant engineering
home-subtitle: Gongyue Teng&ensp;|&ensp;滕宫阅
copyright-text: '&copy; gongyueteng 2023-2025. All Rights Reserved.'
